NAMEEEEEa = Sed

CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

SRC = main.cpp \
	  
OBJ = $(SRC:.cpp=.o)

all: $(NAMEEEEEa)

$(NAMEEEEEa): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAMEEEEEa)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAMEEEEEa)

re: fclean all

.PHONY:		all clean fclean re
